# Generated by Django 5.1.4 on 2024-12-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("lastName", models.CharField(max_length=32)),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "admins",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("lastName", models.CharField(max_length=32)),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="Times",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeIn", models.TimeField()),
                ("timeOut", models.TimeField(default=None, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("singIn", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clockInApp.employee",
                    ),
                ),
            ],
            options={
                "db_table": "times",
            },
        ),
    ]
