# Generated by Django 5.1.4 on 2024-12-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clockInApp", "0002_rename_singin_times_singedin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="times",
            name="singedIn",
        ),
        migrations.AddField(
            model_name="employee",
            name="singedIn",
            field=models.BooleanField(default=False),
        ),
    ]
