# Generated by Django 5.1.4 on 2024-12-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clockInApp", "0003_remove_times_singedin_employee_singedin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="singedIn",
            new_name="signedIn",
        ),
    ]
