# Generated by Django 5.1.4 on 2024-12-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clockInApp", "0004_rename_singedin_employee_signedin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admins",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
